name: dependency-review

on:
  pull_request:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          config-file: it-at-m/.github/workflow-configs/dependency_review.yaml@main
